### ISSUE TITLE
README typo for gradle dependency

### ISSUE THREAD

**Issue by etienne-p** [bertrandmartel/fadecandy-android#1]
the readme suggests using 
compile 'bmartel.fr:fadecandy-service:1.4'
to include the library,
however,
i got it working using 
compile 'fr.bmartel:fadecandy-service:1.4'
(https://bintray.com/bertrandmartel/maven/fadecandy-server-android)

**Comment by bertrandmartel** [comment]
Thank you for noticing this. I've updated the readme
