### ISSUE TITLE
Unable to specify configuration JSON with color order

### ISSUE THREAD

**Issue by cconstantine** [bertrandmartel/fadecandy-android#4]
Hello!

First; thank you so much for making this library.  It's allowed me to put an LED art project's on a Tinkerboard running android.  It's amazing. 

I have some funny ws281x leds that don't have the normal color order.  This is easily fixed by adding a color order mapping to the fadecandy config like so:
```
{
    "listen": ["0.0.0.0", 7890],
    "verbose": true,

    "color": {
        "gamma": 2.5,
        "whitepoint": [0.50, 0.50, 0.50]
    },

    "devices": [
        {
            "type": "fadecandy",
            "map": [
                [ 0, 0,  0, 512, "grb" ]
            ]
        }
    ]
}
```
This is supported by the lastest fadecandy server code at https://github.com/scanlime/fadecandy

When I give that config to your library I get an exception parsing the JSON:
```
01-28 22:32:03.195 13705-13705/org.sillypants.pixo V/FadecandyService: onCreate()
01-28 22:32:03.199 13705-13705/org.sillypants.pixo W/System.err: org.json.JSONException: Value grb at 4 of type java.lang.String cannot be converted to int
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at org.json.JSON.typeMismatch(JSON.java:100)
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at org.json.JSONArray.getInt(JSONArray.java:398)
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at fr.bmartel.android.fadecandy.model.FadecandyDevice.<init>(FadecandyDevice.java:64)
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at fr.bmartel.android.fadecandy.model.FadecandyConfig.<init>(FadecandyConfig.java:79)
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at fr.bmartel.android.fadecandy.service.FadecandyService.onCreate(FadecandyService.java:200)
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at android.app.ActivityThread.-wrap4(ActivityThread.java)
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
01-28 22:32:03.200 13705-13705/org.sillypants.pixo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-28 22:32:03.201 13705-13705/org.sillypants.pixo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
01-28 22:32:03.201 13705-13705/org.sillypants.pixo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
```

**Comment by bertrandmartel** [comment]
Thanks you for opening this issue, I've updated this API  to `setConfig(String config)`, the config string is directly sent to fcserver without parsing on my side : 

```java
mFadecandyClient.setConfig(myConfig);
```
This fix is available in 1.6

If you have the Android app, I've added ability to edit this configuration so you can test it here before using it in your own application 

![device-2018-02-01-200614](https://user-images.githubusercontent.com/5183022/35697828-9d818160-078b-11e8-918d-e878dbdd2a6e.png)

**Comment by cconstantine** [comment]
Thanks!

The update of the fadecandy library fixed the color order parsing, but it appears that the new `setConfig` method doesn't work.  For me to set the new config I still need to set the `fr.bmartel.android.fadecandy.constant.Constants.PREFERENCE_CONFIG` manually: https://github.com/cconstantine/pixo/blob/master/Pixo/app/src/main/java/org/sillypants/pixo/MainActivity.java#L34

I'm happy to leave this issue closed as the JSON parsing is fixed :)

**Comment by bertrandmartel** [comment]
Mm I see, in fact `config` is a property of `FadecandyService` which is initialized inside `FadecandyClient` when the service is connected. In your case the service is not connected yet which is why it doesn't set the config. 

I will add a method `startServer(String config)` in `FadecandyClient` which will start the server after setting the config.

It's unsafe to set `PREFERENCE_CONFIG` since it changes the value in shared preference which is reloaded only when the service starts. So the first time it would not have changed the config until you stopped the service (killed the app) & restarted. So each time you start the server it takes the former config

**Comment by bertrandmartel** [comment]
I've uploaded 1.62 which has the new method, this would work : 

```java
mFadecandyClient.startServer("{\n" +
        "    \"listen\": [\"0.0.0.0\", 7890],\n" +
        "    \"verbose\": true,\n" +
        "\n" +
        "    \"color\": {\n" +
        "        \"gamma\": 2.5,\n" +
        "        \"whitepoint\": [0.50, 0.50, 0.50]\n" +
        "    },\n" +
        "\n" +
        "    \"devices\": [\n" +
        "        {\n" +
        "            \"type\": \"fadecandy\",\n" +
        "            \"map\": [\n" +
        "                [ 0, 0,  0, 512, \"grb\"]\n" +
        "            ]\n" +
        "        }\n" +
        "    ]\n" +
        "}\n");
```
let me know if you have any problem

**Comment by cconstantine** [comment]
That appears to have done it.

Thanks :)
